#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [--tests] [--types]"
	exit 2
}

tests=false
types=false
for arg
do
	case "$arg" in
		--tests) tests=true ;;
		--types) types=true ;;
		*) usage ;;
	esac
done

if ! $tests && ! $types
then
	tests=true
	types=true
fi

cfg=src/config.py
if ! test -e "$cfg"
then
	echo >&2 "Creating dummy config.py..."

	cat >"$cfg" <<!
slack_token = "invalid"
user_renames = {}
channel_max_players = {}
private_channels = []
!
fi

ec=0

if $tests
then
	for f in $(find src -iname '*.spec.py')
	do
		if ! python3 "$f"
		then ec=1
		fi
	done
fi

if $types
then
	if ! (cd src && pyright **/*.py)
	then ec=1
	fi
fi

exit $ec
