#!/bin/sh

if test $# -ne 0
then
	echo >&2 "Usage: $0"
	exit 2
fi

cfg=src/config.py
if ! test -e "$cfg"
then
	echo >&2 "Creating dummy config.py..."

	cat >"$cfg" <<!
slack_token = "invalid"
user_renames = {}
channel_max_players = {}
!
fi

ec=0

for f in $(find src -iname '*.spec.py')
do
	if ! python "$f"
	then ec=1
	fi
done

exit $ec
